-- Create sales_data table
CREATE TABLE IF NOT EXISTS sales_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    product TEXT NOT NULL,
    channel TEXT NOT NULL,
    orders INTEGER DEFAULT 0,
    revenue DECIMAL(12, 2) DEFAULT 0.00,
    cost DECIMAL(12, 2) DEFAULT 0.00,
    visitors INTEGER DEFAULT 0,
    customers INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Optional: Enable Row Level Security (RLS)
-- ALTER TABLE sales_data ENABLE ROW LEVEL SECURITY;

-- Optional: Create a policy to allow all to read (adjust for production)
-- CREATE POLICY "Allow public read access" ON sales_data FOR SELECT USING (true);
